version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./matcha_backend:/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
    networks:
      - matcha-network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - matcha-network

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - ./front:/front
    ports:
      - 5173:5173
    networks:
      - matcha-network

networks:
  matcha-network:
    name: matcha-network
    driver: bridge


volumes:
  mongodb_data:
