export const DEFAULT_ALL_RESULTS_SORTING_PROP = 'distance';
export const DEFAULT_ALL_RESULTS_SORTING_ORDER = 'asc';

export const SORTING_ORDER = {
	ASC: 'asc',
	DESC: 'desc'
};

export const SORTING_LS_KEY = 'SORTING_CRITERIA';
export const FILTERS_LS_KEY = 'FILTERS_CRITERIA';

export const SUGGESTIONS_SORTING_LS_KEY = 'SUGGESTIONS_SORTING_CRITERIA';

export const SUGGESTIONS_COMMON_INTERESTS = '2';
export const SUGGESTIONS_MAX_DISTANCE = '5';
